name: Install UV Package
description: Installs the UV package in Python

runs:
  using: "composite"
  steps:
    - name: Install xmlsec1 dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libxml2-dev libxmlsec1-dev libxmlsec1-openssl
      shell: bash

    - name: Set up Python
      uses: actions/setup-python@v5.3.0
      with:
        python-version: '3.12'
    
    - name: Install xmlsec
      run: pip install xmlsec==1.3.15
      shell: bash

    - name: Install uv package
      run: |
        python -m pip install --upgrade pip
        pip install uv==0.5.21
      shell: bash