name: Comment on PR

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Comment on the pull request
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const commentBody = "👋 Thanks for your PR! A maintainer will review it shortly.";

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: commentBody,
            });
