name: PR Title Format Check

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
  merge_group:

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title format
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            if (!pr) {
              core.warning("⚠️ No pull_request context found (maybe running locally with act). Skipping description check.");
              return;
            }       
            const title = pr?.title ?? "";

            // Matches: [Ticket] Action: Description
            const pattern = /^\[[A-Z]+-\d+\]\s\S+(?:\([^)]+\))?:\s.+$/

            if (!pattern.test(title)) {
              core.setFailed(`❌ PR title "${title}" does not match the required format like "[TEST-123] Action: Description".`);
            } else {
              console.log("✅ PR title format is valid.");
            }
