name: Test Action

on:
  pull_request:
    branches:
      - main
  merge_group:
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
    - name: install uv
      uses: ./.github/actions/install_uv
    - name: Run Main
      run: |
        uv run main.py
